"""
1. Read the Log in Real-Time (Continuous Stream): tail -f surveillance.log
2. Filter for Specific Columns: cat surveillance.log | awk -F'|' '{print $1 $2}'
3. Search for a Specific Track ID: grep "Tracking ID: 1 " surveillance.log
4. Read the Entire File From the Beginning: less surveillance.log
"""

import argparse
from pathlib import Path

def parse_tracking_log(log_file_path: str):
    log_path = Path(log_file_path)
    
    if not log_path.exists():
        print(f"[Error] Log file not found at: {log_file_path}")
        return

    # Print a clean 3-column header layout
    print(f"\n{'='*56}")
    print(f"{'TRACK ID':<10} | {'TIMESTAMP':<25} | {'YOLO CONF':<10}")
    print(f"{'='*56}")

    parsed_count = 0

    with open(log_path, "r", encoding="utf-8") as f:
        for line in f:
            line_str = line.strip()
            
            # Target lines generated by our tracking system loop
            if "[TRACK UPDATE]" in line_str and "|" in line_str:
                try:
                    parts = line_str.split("|")
                    if len(parts) >= 2:
                        # 1. Parse Timestamp & Track ID from the first segment
                        # Example: "2026-09-27 07:22:14,302 - INFO - [TRACK UPDATE] Tracking ID: 1 "
                        first_segment = parts[0].split(" - ")
                        timestamp = first_segment[0].strip()
                        track_id = first_segment[-1].split("Tracking ID:")[-1].strip()

                        # 2. Parse Confidence Score from the second segment
                        # Example: " Conf: 0.92 "
                        yolo_conf = parts[1].split("Conf:")[-1].strip()

                        # Print clean 3-column rows matching the new request
                        print(f"{track_id:<10} | {timestamp:<25} | {yolo_conf:<10}")
                        parsed_count += 1
                except Exception:
                    # Skip any single corrupt line silently to prevent crashing the stream
                    continue

    print(f"{'='*56}")
    print(f"Total entries parsed successfully: {parsed_count}\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--log", type=str, default="surveillance.log", help="Path to the log file")
    args = parser.parse_args()

    parse_tracking_log(args.log)
